[package]
name = "lints"
version = "0.1.0"
edition = "2024"

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "428208e" }

[dev-dependencies]
prettydiff = "0.8.0"

[[test]]
name = "uitest"
harness = false

[package.metadata.rust-analyzer]
rustc_private = true
