use dash_proc_macro::Trace;

use crate::gc::{Allocator, ObjectId};
use crate::js_std;
use crate::value::PureBuiltin;
use crate::value::error::{AggregateError, EvalError, RangeError, ReferenceError, SyntaxError, TypeError, URIError};
use crate::value::function::{Function, FunctionKind};
use crate::value::map::Map;
use crate::value::regex::RegExp;
use crate::value::set::Set;
use crate::value::weakmap::WeakMap;
use crate::value::weakset::WeakSet;
use dash_middle::interner::{self, sym};

use super::value::array::{Array, ArrayIterator};
use super::value::arraybuffer::ArrayBuffer;
use super::value::boxed::{
    Boolean as BoxedBoolean, Number as BoxedNumber, String as BoxedString, Symbol as BoxedSymbol,
};
use super::value::error::Error;
use super::value::function::generator::GeneratorIterator;
use super::value::function::native::NativeFunction;
use super::value::object::{Object, OrdObject};
use super::value::primitive::Symbol;

#[derive(Trace)]
pub struct Statics {
    pub function_proto: ObjectId,
    pub function_ctor: ObjectId,
    pub function_apply: ObjectId,
    pub function_bind: ObjectId,
    pub function_call: ObjectId,
    pub function_to_string: ObjectId,
    pub is_nan: ObjectId,
    pub eval: ObjectId,
    pub is_finite: ObjectId,
    pub parse_float: ObjectId,
    pub parse_int: ObjectId,
    pub console: ObjectId,
    pub console_log: ObjectId,
    pub console_error: ObjectId,
    pub math: ObjectId,
    pub math_floor: ObjectId,
    pub math_abs: ObjectId,
    pub math_acos: ObjectId,
    pub math_acosh: ObjectId,
    pub math_asin: ObjectId,
    pub math_asinh: ObjectId,
    pub math_atan: ObjectId,
    pub math_atanh: ObjectId,
    pub math_atan2: ObjectId,
    pub math_cbrt: ObjectId,
    pub math_ceil: ObjectId,
    pub math_clz32: ObjectId,
    pub math_cos: ObjectId,
    pub math_cosh: ObjectId,
    pub math_exp: ObjectId,
    pub math_expm1: ObjectId,
    pub math_log: ObjectId,
    pub math_log1p: ObjectId,
    pub math_log10: ObjectId,
    pub math_log2: ObjectId,
    pub math_round: ObjectId,
    pub math_sin: ObjectId,
    pub math_sinh: ObjectId,
    pub math_sqrt: ObjectId,
    pub math_tan: ObjectId,
    pub math_tanh: ObjectId,
    pub math_trunc: ObjectId,
    pub math_random: ObjectId,
    pub math_max: ObjectId,
    pub math_min: ObjectId,
    pub math_pow: ObjectId,
    pub object_ctor: ObjectId,
    pub object_prototype: ObjectId,
    pub object_create: ObjectId,
    pub object_keys: ObjectId,
    pub object_get_own_property_names: ObjectId,
    pub object_get_own_property_symbols: ObjectId,
    pub object_to_string: ObjectId,
    pub object_get_own_property_descriptor: ObjectId,
    pub object_get_own_property_descriptors: ObjectId,
    pub object_has_own_property: ObjectId,
    pub object_define_property: ObjectId,
    pub object_define_properties: ObjectId,
    pub object_assign: ObjectId,
    pub object_entries: ObjectId,
    pub object_freeze: ObjectId,
    pub object_seal: ObjectId,
    pub object_get_prototype_of: ObjectId,
    pub object_set_prototype_of: ObjectId,
    pub object_is_prototype_of: ObjectId,
    pub object_property_is_enumerable: ObjectId,
    pub number_ctor: ObjectId,
    pub number_prototype: ObjectId,
    pub number_tostring: ObjectId,
    pub number_valueof: ObjectId,
    pub number_is_finite: ObjectId,
    pub number_is_nan: ObjectId,
    pub number_is_safe_integer: ObjectId,
    pub number_is_integer: ObjectId,
    pub number_to_fixed: ObjectId,
    pub boolean_ctor: ObjectId,
    pub boolean_tostring: ObjectId,
    pub boolean_prototype: ObjectId,
    pub boolean_valueof: ObjectId,
    pub string_ctor: ObjectId,
    pub string_prototype: ObjectId,
    pub string_tostring: ObjectId,
    pub string_char_at: ObjectId,
    pub string_char_code_at: ObjectId,
    pub string_concat: ObjectId,
    pub string_ends_with: ObjectId,
    pub string_starts_with: ObjectId,
    pub string_includes: ObjectId,
    pub string_index_of: ObjectId,
    pub string_last_index_of: ObjectId,
    pub string_pad_end: ObjectId,
    pub string_pad_start: ObjectId,
    pub string_repeat: ObjectId,
    pub string_replace: ObjectId,
    pub string_replace_all: ObjectId,
    pub string_split: ObjectId,
    pub string_to_uppercase: ObjectId,
    pub string_to_lowercase: ObjectId,
    pub string_big: ObjectId,
    pub string_blink: ObjectId,
    pub string_bold: ObjectId,
    pub string_fixed: ObjectId,
    pub string_italics: ObjectId,
    pub string_strike: ObjectId,
    pub string_sub: ObjectId,
    pub string_sup: ObjectId,
    pub string_fontcolor: ObjectId,
    pub string_fontsize: ObjectId,
    pub string_link: ObjectId,
    pub string_trim: ObjectId,
    pub string_trim_start: ObjectId,
    pub string_trim_end: ObjectId,
    pub string_from_char_code: ObjectId,
    pub string_substr: ObjectId,
    pub string_substring: ObjectId,
    pub string_slice: ObjectId,
    pub string_iterator: ObjectId,
    pub array_ctor: ObjectId,
    pub array_tostring: ObjectId,
    pub array_prototype: ObjectId,
    pub array_join: ObjectId,
    pub array_values: ObjectId,
    pub symbol_ctor: ObjectId,
    pub symbol_prototype: ObjectId,
    pub symbol_async_iterator: Symbol,
    pub symbol_has_instance: Symbol,
    pub symbol_is_concat_spreadable: Symbol,
    pub symbol_iterator: Symbol,
    pub symbol_match: Symbol,
    pub symbol_match_all: Symbol,
    pub symbol_replace: Symbol,
    pub symbol_search: Symbol,
    pub symbol_species: Symbol,
    pub symbol_split: Symbol,
    pub symbol_to_primitive: Symbol,
    pub symbol_to_string_tag: Symbol,
    pub symbol_unscopables: Symbol,
    pub array_iterator_prototype: ObjectId,
    pub array_iterator_next: ObjectId,
    pub self_iterator: ObjectId,
    pub array_at: ObjectId,
    pub array_concat: ObjectId,
    pub array_entries: ObjectId,
    pub array_keys: ObjectId,
    pub array_every: ObjectId,
    pub array_some: ObjectId,
    pub array_fill: ObjectId,
    pub array_filter: ObjectId,
    pub array_reduce: ObjectId,
    pub array_find: ObjectId,
    pub array_find_index: ObjectId,
    pub array_flat: ObjectId,
    pub array_for_each: ObjectId,
    pub array_includes: ObjectId,
    pub array_index_of: ObjectId,
    pub array_map: ObjectId,
    pub array_pop: ObjectId,
    pub array_push: ObjectId,
    pub array_reverse: ObjectId,
    pub array_shift: ObjectId,
    pub array_sort: ObjectId,
    pub array_splice: ObjectId,
    pub array_unshift: ObjectId,
    pub array_slice: ObjectId,
    pub array_last_index_of: ObjectId,
    pub array_from: ObjectId,
    pub array_is_array: ObjectId,
    pub generator_iterator_prototype: ObjectId,
    pub generator_iterator_next: ObjectId,
    pub generator_iterator_throw: ObjectId,
    pub error_ctor: ObjectId,
    pub error_prototype: ObjectId,
    pub error_to_string: ObjectId,
    pub eval_error_ctor: ObjectId,
    pub eval_error_prototype: ObjectId,
    pub range_error_ctor: ObjectId,
    pub range_error_prototype: ObjectId,
    pub reference_error_ctor: ObjectId,
    pub reference_error_prototype: ObjectId,
    pub syntax_error_ctor: ObjectId,
    pub syntax_error_prototype: ObjectId,
    pub type_error_ctor: ObjectId,
    pub type_error_prototype: ObjectId,
    pub uri_error_ctor: ObjectId,
    pub uri_error_prototype: ObjectId,
    pub aggregate_error_ctor: ObjectId,
    pub aggregate_error_prototype: ObjectId,
    pub arraybuffer_ctor: ObjectId,
    pub arraybuffer_prototype: ObjectId,
    pub arraybuffer_byte_length: ObjectId,
    pub uint8array_ctor: ObjectId,
    pub uint8array_prototype: ObjectId,
    pub int8array_ctor: ObjectId,
    pub int8array_prototype: ObjectId,
    pub uint16array_ctor: ObjectId,
    pub uint16array_prototype: ObjectId,
    pub int16array_ctor: ObjectId,
    pub int16array_prototype: ObjectId,
    pub uint32array_ctor: ObjectId,
    pub uint32array_prototype: ObjectId,
    pub int32array_ctor: ObjectId,
    pub int32array_prototype: ObjectId,
    pub float32array_ctor: ObjectId,
    pub float32array_prototype: ObjectId,
    pub float64array_ctor: ObjectId,
    pub float64array_prototype: ObjectId,
    pub typedarray_fill: ObjectId,
    pub promise_ctor: ObjectId,
    pub promise_proto: ObjectId,
    pub promise_resolve: ObjectId,
    pub promise_reject: ObjectId,
    pub promise_then: ObjectId,
    pub set_constructor: ObjectId,
    pub set_prototype: ObjectId,
    pub set_add: ObjectId,
    pub set_has: ObjectId,
    pub set_delete: ObjectId,
    pub set_clear: ObjectId,
    pub set_size: ObjectId,
    pub map_constructor: ObjectId,
    pub map_prototype: ObjectId,
    pub map_set: ObjectId,
    pub map_get: ObjectId,
    pub map_has: ObjectId,
    pub map_delete: ObjectId,
    pub map_clear: ObjectId,
    pub map_size: ObjectId,
    pub weakmap_constructor: ObjectId,
    pub weakmap_prototype: ObjectId,
    pub weakmap_set: ObjectId,
    pub weakmap_has: ObjectId,
    pub weakmap_get: ObjectId,
    pub weakmap_delete: ObjectId,
    pub weakset_constructor: ObjectId,
    pub weakset_prototype: ObjectId,
    pub weakset_add: ObjectId,
    pub weakset_has: ObjectId,
    pub weakset_delete: ObjectId,
    pub regexp_ctor: ObjectId,
    pub regexp_prototype: ObjectId,
    pub regexp_test: ObjectId,
    pub regexp_exec: ObjectId,
    pub date_ctor: ObjectId,
    pub date_prototype: ObjectId,
    pub date_get_time: ObjectId,
    pub date_now: ObjectId,
    pub json_ctor: ObjectId,
    pub json_parse: ObjectId,
}

fn builtin_object<O: Object + 'static>(gc: &mut Allocator, obj: O) -> ObjectId {
    gc.alloc_object(PureBuiltin::new(obj))
}

fn empty_object(gc: &mut Allocator) -> ObjectId {
    gc.alloc_object(OrdObject::null())
}

fn function(gc: &mut Allocator, name: interner::Symbol, function: NativeFunction, constructable: bool) -> ObjectId {
    Function::alloc_with_obj(
        gc,
        Some(name.into()),
        FunctionKind::Native {
            function,
            constructable,
        },
        OrdObject::null(),
    )
}

impl Statics {
    pub fn new(gc: &mut Allocator) -> Self {
        Self {
            function_proto: empty_object(gc),
            function_ctor: function(gc, sym::Function, js_std::function::constructor, true),
            function_apply: function(gc, sym::apply, js_std::function::apply, false),
            function_bind: function(gc, sym::bind, js_std::function::bind, false),
            function_call: function(gc, sym::call, js_std::function::call, false),
            function_to_string: function(gc, sym::toString, js_std::function::to_string, false),
            console: empty_object(gc),
            console_log: function(gc, sym::log, js_std::global::log_stdout, false),
            console_error: function(gc, sym::error, js_std::global::log_stderr, false),
            math: empty_object(gc),
            math_floor: function(gc, sym::floor, js_std::math::floor, false),
            object_ctor: function(gc, sym::object, js_std::object::constructor, true),
            object_create: function(gc, sym::create, js_std::object::create, false),
            object_keys: function(gc, sym::keys, js_std::object::keys, false),
            object_get_own_property_names: function(
                gc,
                sym::getOwnPropertyNames,
                js_std::object::get_own_property_names,
                false,
            ),
            object_get_own_property_symbols: function(
                gc,
                sym::getOwnPropertySymbols,
                js_std::object::get_own_property_symbols,
                false,
            ),
            object_prototype: empty_object(gc),
            object_to_string: function(gc, sym::toString, js_std::object::to_string, false),
            object_get_own_property_descriptor: function(
                gc,
                sym::getOwnPropertyDescriptor,
                js_std::object::get_own_property_descriptor,
                false,
            ),
            object_get_own_property_descriptors: function(
                gc,
                sym::getOwnPropertyDescriptors,
                js_std::object::get_own_property_descriptors,
                false,
            ),
            object_has_own_property: function(gc, sym::hasOwnProperty, js_std::object::has_own_property, false),
            object_define_property: function(gc, sym::defineProperty, js_std::object::define_property, false),
            object_define_properties: function(gc, sym::defineProperties, js_std::object::define_properties, false),
            object_assign: function(gc, sym::assign, js_std::object::assign, false),
            object_entries: function(gc, sym::entries, js_std::object::entries, false),
            object_get_prototype_of: function(gc, sym::getPrototypeOf, js_std::object::get_prototype_of, false),
            object_set_prototype_of: function(gc, sym::setPrototypeOf, js_std::object::set_prototype_of, false),
            object_is_prototype_of: function(gc, sym::isPrototypeOf, js_std::object::is_prototype_of, false),
            object_property_is_enumerable: function(
                gc,
                sym::propertyIsEnumerable,
                js_std::object::property_is_enumerable,
                false,
            ),
            object_freeze: function(gc, sym::freeze, js_std::object::freeze, false),
            object_seal: function(gc, sym::seal, js_std::object::seal, false),
            number_ctor: function(gc, sym::Number, js_std::number::constructor, true),
            number_prototype: builtin_object(gc, BoxedNumber::with_obj(0.0, OrdObject::null())),
            number_tostring: function(gc, sym::toString, js_std::number::to_string, false),
            number_valueof: function(gc, sym::valueOf, js_std::number::value_of, false),
            boolean_ctor: function(gc, sym::Boolean, js_std::boolean::constructor, true),
            boolean_tostring: function(gc, sym::toString, js_std::boolean::to_string, false),
            boolean_prototype: builtin_object(gc, BoxedBoolean::with_obj(false, OrdObject::null())),
            string_ctor: function(gc, sym::String, js_std::string::constructor, true),
            string_prototype: builtin_object(gc, BoxedString::with_obj(sym::empty.into(), OrdObject::null())),
            is_nan: function(gc, sym::isNaN, js_std::global::is_nan, false),
            eval: function(gc, sym::eval, js_std::global::eval, false),
            is_finite: function(gc, sym::isFinite, js_std::global::is_finite, false),
            parse_float: function(gc, sym::parseFloat, js_std::global::parse_float, false),
            parse_int: function(gc, sym::parseInt, js_std::global::parse_int, false),
            math_abs: function(gc, sym::abs, js_std::math::abs, false),
            math_acos: function(gc, sym::acos, js_std::math::acos, false),
            math_acosh: function(gc, sym::acosh, js_std::math::acosh, false),
            math_asin: function(gc, sym::asin, js_std::math::asin, false),
            math_asinh: function(gc, sym::asinh, js_std::math::asinh, false),
            math_atan: function(gc, sym::atan, js_std::math::atan, false),
            math_atanh: function(gc, sym::atanh, js_std::math::atanh, false),
            math_atan2: function(gc, sym::atan2, js_std::math::atan2, false),
            math_cbrt: function(gc, sym::cbrt, js_std::math::cbrt, false),
            math_ceil: function(gc, sym::ceil, js_std::math::ceil, false),
            math_clz32: function(gc, sym::clz32, js_std::math::clz32, false),
            math_cos: function(gc, sym::cos, js_std::math::cos, false),
            math_cosh: function(gc, sym::cosh, js_std::math::cosh, false),
            math_exp: function(gc, sym::exp, js_std::math::exp, false),
            math_expm1: function(gc, sym::expm1, js_std::math::expm1, false),
            math_log: function(gc, sym::log, js_std::math::log, false),
            math_log1p: function(gc, sym::log1p, js_std::math::log1p, false),
            math_log10: function(gc, sym::log10, js_std::math::log10, false),
            math_log2: function(gc, sym::log2, js_std::math::log2, false),
            math_round: function(gc, sym::round, js_std::math::round, false),
            math_sin: function(gc, sym::sin, js_std::math::sin, false),
            math_sinh: function(gc, sym::sinh, js_std::math::sinh, false),
            math_sqrt: function(gc, sym::sqrt, js_std::math::sqrt, false),
            math_tan: function(gc, sym::tan, js_std::math::tan, false),
            math_tanh: function(gc, sym::tanh, js_std::math::tanh, false),
            math_trunc: function(gc, sym::trunc, js_std::math::trunc, false),
            math_random: function(gc, sym::random, js_std::math::random, false),
            math_max: function(gc, sym::max, js_std::math::max, false),
            math_min: function(gc, sym::min, js_std::math::min, false),
            math_pow: function(gc, sym::pow, js_std::math::pow, false),
            number_is_finite: function(gc, sym::isFinite, js_std::number::is_finite, false),
            number_is_nan: function(gc, sym::isNaN, js_std::number::is_nan, false),
            number_is_safe_integer: function(gc, sym::isSafeInteger, js_std::number::is_safe_integer, false),
            number_is_integer: function(gc, sym::isInteger, js_std::number::is_integer, false),
            number_to_fixed: function(gc, sym::toFixed, js_std::number::to_fixed, false),
            boolean_valueof: function(gc, sym::valueOf, js_std::boolean::value_of, false),
            string_tostring: function(gc, sym::toString, js_std::string::to_string, false),
            string_char_at: function(gc, sym::charAt, js_std::string::char_at, false),
            string_char_code_at: function(gc, sym::charCodeAt, js_std::string::char_code_at, false),
            string_concat: function(gc, sym::concat, js_std::string::concat, false),
            string_ends_with: function(gc, sym::endsWith, js_std::string::ends_with, false),
            string_starts_with: function(gc, sym::startsWith, js_std::string::starts_with, false),
            string_includes: function(gc, sym::includes, js_std::string::includes, false),
            string_index_of: function(gc, sym::indexOf, js_std::string::index_of, false),
            string_last_index_of: function(gc, sym::lastIndexOf, js_std::string::last_index_of, false),
            string_pad_end: function(gc, sym::padEnd, js_std::string::pad_end, false),
            string_pad_start: function(gc, sym::padStart, js_std::string::pad_start, false),
            string_repeat: function(gc, sym::repeat, js_std::string::repeat, false),
            string_replace: function(gc, sym::replace, js_std::string::replace, false),
            string_replace_all: function(gc, sym::replaceAll, js_std::string::replace_all, false),
            string_split: function(gc, sym::split, js_std::string::split, false),
            string_to_uppercase: function(gc, sym::toUpperCase, js_std::string::to_uppercase, false),
            string_to_lowercase: function(gc, sym::toLowerCase, js_std::string::to_lowercase, false),
            string_big: function(gc, sym::big, js_std::string::big, false),
            string_blink: function(gc, sym::blink, js_std::string::blink, false),
            string_bold: function(gc, sym::bold, js_std::string::bold, false),
            string_fixed: function(gc, sym::fixed, js_std::string::fixed, false),
            string_italics: function(gc, sym::italics, js_std::string::italics, false),
            string_strike: function(gc, sym::strike, js_std::string::strike, false),
            string_sub: function(gc, sym::sub, js_std::string::sub, false),
            string_sup: function(gc, sym::sup, js_std::string::sup, false),
            string_fontcolor: function(gc, sym::fontcolor, js_std::string::fontcolor, false),
            string_fontsize: function(gc, sym::fontsize, js_std::string::fontsize, false),
            string_link: function(gc, sym::link, js_std::string::link, false),
            string_trim: function(gc, sym::trim, js_std::string::trim, false),
            string_trim_start: function(gc, sym::trimStart, js_std::string::trim_start, false),
            string_trim_end: function(gc, sym::trimEnd, js_std::string::trim_end, false),
            string_from_char_code: function(gc, sym::fromCharCode, js_std::string::from_char_code, false),
            string_substr: function(gc, sym::substr, js_std::string::substr, false),
            string_substring: function(gc, sym::substring, js_std::string::substring, false),
            string_slice: function(gc, sym::slice, js_std::string::slice, false),
            string_iterator: function(gc, sym::iterator, js_std::string::iterator, false),
            array_ctor: function(gc, sym::Array, js_std::array::constructor, true),
            array_tostring: function(gc, sym::toString, js_std::array::to_string, false),
            array_prototype: builtin_object(gc, Array::with_obj(OrdObject::null())),
            array_join: function(gc, sym::join, js_std::array::join, false),
            array_values: function(gc, sym::values, js_std::array::values, false),
            array_reverse: function(gc, sym::reverse, js_std::array::reverse, false),
            symbol_ctor: function(gc, sym::JsSymbol, js_std::symbol::constructor, true),
            symbol_prototype: builtin_object(
                gc,
                BoxedSymbol::with_obj(Symbol::new(sym::empty.into()), OrdObject::null()),
            ),
            symbol_async_iterator: Symbol::new(sym::asyncIterator.into()),
            symbol_has_instance: Symbol::new(sym::hasInstance.into()),
            symbol_is_concat_spreadable: Symbol::new(sym::isConcatSpreadable.into()),
            symbol_iterator: Symbol::new(sym::iterator.into()),
            symbol_match: Symbol::new(sym::match_.into()),
            symbol_match_all: Symbol::new(sym::matchAll.into()),
            symbol_replace: Symbol::new(sym::replace.into()),
            symbol_search: Symbol::new(sym::search.into()),
            symbol_species: Symbol::new(sym::species.into()),
            symbol_split: Symbol::new(sym::split.into()),
            symbol_to_primitive: Symbol::new(sym::toPrimitive.into()),
            symbol_to_string_tag: Symbol::new(sym::toStringTag.into()),
            symbol_unscopables: Symbol::new(sym::unscopables.into()),
            array_iterator_prototype: builtin_object(gc, ArrayIterator::empty()),
            array_iterator_next: function(gc, sym::next, js_std::array_iterator::next, false),
            self_iterator: function(gc, sym::iterator, js_std::identity_this, false),
            array_at: function(gc, sym::at, js_std::array::at, false),
            array_concat: function(gc, sym::concat, js_std::array::concat, false),
            array_entries: function(gc, sym::entries, js_std::array::entries, false),
            array_keys: function(gc, sym::keys, js_std::array::keys, false),
            array_every: function(gc, sym::every, js_std::array::every, false),
            array_some: function(gc, sym::some, js_std::array::some, false),
            array_fill: function(gc, sym::fill, js_std::array::fill, false),
            array_filter: function(gc, sym::filter, js_std::array::filter, false),
            array_reduce: function(gc, sym::reduce, js_std::array::reduce, false),
            array_find: function(gc, sym::find, js_std::array::find, false),
            array_find_index: function(gc, sym::findIndex, js_std::array::find_index, false),
            array_flat: function(gc, sym::flat, js_std::array::flat, false),
            array_for_each: function(gc, sym::forEach, js_std::array::for_each, false),
            array_includes: function(gc, sym::includes, js_std::array::includes, false),
            array_index_of: function(gc, sym::indexOf, js_std::array::index_of, false),
            array_map: function(gc, sym::map, js_std::array::map, false),
            array_pop: function(gc, sym::pop, js_std::array::pop, false),
            array_push: function(gc, sym::push, js_std::array::push, false),
            array_shift: function(gc, sym::shift, js_std::array::shift, false),
            array_sort: function(gc, sym::sort, js_std::array::sort, false),
            array_unshift: function(gc, sym::unshift, js_std::array::unshift, false),
            array_slice: function(gc, sym::slice, js_std::array::slice, false),
            array_splice: function(gc, sym::splice, js_std::array::splice, false),
            array_last_index_of: function(gc, sym::lastIndexOf, js_std::array::last_index_of, false),
            array_from: function(gc, sym::from, js_std::array::from, false),
            array_is_array: function(gc, sym::isArray, js_std::array::is_array, false),
            generator_iterator_prototype: {
                let obj: ObjectId = empty_object(gc);
                builtin_object(gc, GeneratorIterator::empty(obj))
            },
            generator_iterator_next: function(gc, sym::next, js_std::generator::next, false),
            generator_iterator_throw: function(gc, sym::throw, js_std::generator::throw, false),
            error_ctor: function(gc, sym::Error, js_std::error::error_constructor, true),
            error_prototype: builtin_object(gc, Error::empty()),
            error_to_string: function(gc, sym::toString, js_std::error::to_string, false),
            eval_error_ctor: function(gc, sym::EvalError, js_std::error::eval_error_constructor, true),
            eval_error_prototype: builtin_object(gc, EvalError::empty()),
            range_error_ctor: function(gc, sym::RangeError, js_std::error::range_error_constructor, true),
            range_error_prototype: builtin_object(gc, RangeError::empty()),
            reference_error_ctor: function(
                gc,
                sym::ReferenceError,
                js_std::error::reference_error_constructor,
                true,
            ),
            reference_error_prototype: builtin_object(gc, ReferenceError::empty()),
            syntax_error_ctor: function(gc, sym::SyntaxError, js_std::error::syntax_error_constructor, true),
            syntax_error_prototype: builtin_object(gc, SyntaxError::empty()),
            type_error_ctor: function(gc, sym::TypeError, js_std::error::type_error_constructor, true),
            type_error_prototype: builtin_object(gc, TypeError::empty()),
            uri_error_ctor: function(gc, sym::URIError, js_std::error::uri_error_constructor, true),
            uri_error_prototype: builtin_object(gc, URIError::empty()),
            aggregate_error_ctor: function(
                gc,
                sym::AggregateError,
                js_std::error::aggregate_error_constructor,
                true,
            ),
            aggregate_error_prototype: builtin_object(gc, AggregateError::empty()),
            arraybuffer_ctor: function(gc, sym::ArrayBuffer, js_std::arraybuffer::constructor, true),
            arraybuffer_prototype: builtin_object(gc, ArrayBuffer::empty()),
            arraybuffer_byte_length: function(gc, sym::byteLength, js_std::arraybuffer::byte_length, false),
            uint8array_ctor: function(gc, sym::Uint8Array, js_std::typedarray::u8array::constructor, true),
            uint8array_prototype: empty_object(gc),
            int8array_ctor: function(gc, sym::Int8Array, js_std::typedarray::i8array::constructor, true),
            int8array_prototype: empty_object(gc),
            uint16array_ctor: function(gc, sym::Uint16Array, js_std::typedarray::u16array::constructor, true),
            uint16array_prototype: empty_object(gc),
            int16array_ctor: function(gc, sym::Int16Array, js_std::typedarray::i16array::constructor, true),
            int16array_prototype: empty_object(gc),
            uint32array_ctor: function(gc, sym::Uint32Array, js_std::typedarray::u32array::constructor, true),
            uint32array_prototype: empty_object(gc),
            int32array_ctor: function(gc, sym::Int32Array, js_std::typedarray::i32array::constructor, true),
            int32array_prototype: empty_object(gc),
            float32array_ctor: function(gc, sym::Float32Array, js_std::typedarray::f32array::constructor, true),
            float32array_prototype: empty_object(gc),
            float64array_ctor: function(gc, sym::Float64Array, js_std::typedarray::f64array::constructor, true),
            float64array_prototype: empty_object(gc),
            typedarray_fill: function(gc, sym::fill, js_std::typedarray::fill, false),
            promise_ctor: function(gc, sym::Promise, js_std::promise::constructor, true),
            promise_proto: empty_object(gc),
            promise_resolve: function(gc, sym::resolve, js_std::promise::resolve, false),
            promise_reject: function(gc, sym::reject, js_std::promise::reject, false),
            promise_then: function(gc, sym::then, js_std::promise::then, false),
            set_constructor: function(gc, sym::Set, js_std::set::constructor, true),
            set_add: function(gc, sym::add, js_std::set::add, false),
            set_has: function(gc, sym::has, js_std::set::has, false),
            set_delete: function(gc, sym::delete, js_std::set::delete, false),
            set_prototype: builtin_object(gc, Set::with_obj(OrdObject::null())),
            set_clear: function(gc, sym::clear, js_std::set::clear, false),
            set_size: function(gc, sym::size, js_std::set::size, false),
            map_constructor: function(gc, sym::Map, js_std::map::constructor, true),
            map_set: function(gc, sym::set, js_std::map::set, false),
            map_get: function(gc, sym::get, js_std::map::get, false),
            map_has: function(gc, sym::has, js_std::map::has, false),
            map_delete: function(gc, sym::delete, js_std::map::delete, false),
            map_prototype: builtin_object(gc, Map::with_obj(OrdObject::null())),
            map_clear: function(gc, sym::clear, js_std::map::clear, false),
            map_size: function(gc, sym::size, js_std::map::size, false),
            regexp_ctor: function(gc, sym::RegExp, js_std::regex::constructor, true),
            regexp_prototype: builtin_object(gc, RegExp::empty()),
            regexp_test: function(gc, sym::test, js_std::regex::test, false),
            regexp_exec: function(gc, sym::exec, js_std::regex::exec, false),
            date_ctor: function(gc, sym::Date, js_std::date::constructor, true),
            date_prototype: builtin_object(gc, OrdObject::null()),
            date_now: function(gc, sym::now, js_std::date::now, false),
            date_get_time: function(gc, sym::getTime, js_std::date::get_time, false),
            json_ctor: function(gc, sym::JSON, js_std::json::constructor, true),
            json_parse: function(gc, sym::parse, js_std::json::parse, false),
            weakmap_constructor: function(gc, sym::WeakMap, js_std::weakmap::constructor, true),
            weakmap_prototype: builtin_object(gc, WeakMap::null()),
            weakmap_set: function(gc, sym::set, js_std::weakmap::set, false),
            weakmap_has: function(gc, sym::has, js_std::weakmap::has, false),
            weakmap_get: function(gc, sym::get, js_std::weakmap::get, false),
            weakmap_delete: function(gc, sym::delete, js_std::weakmap::delete, false),
            weakset_constructor: function(gc, sym::WeakSet, js_std::weakset::constructor, true),
            weakset_prototype: builtin_object(gc, WeakSet::null()),
            weakset_add: function(gc, sym::add, js_std::weakset::add, false),
            weakset_has: function(gc, sym::has, js_std::weakset::has, false),
            weakset_delete: function(gc, sym::delete, js_std::weakset::delete, false),
        }
    }
}
