[package]
name = "dash_optimizer"
version = "0.3.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dash_middle = { path = "../dash_middle" }
dash_log = { path = "../dash_log" }
